# Generated by Django 4.1.2 on 2022-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
